services:
  app:
    build: .
    container_name: laravel_app_prod
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - "8000:8000"
    entrypoint: /usr/local/bin/docker-entrypoint.sh
    command: php artisan serve --host=0.0.0.0 --port=8000
    environment:
      - DB_HOST=db
      - DB_DATABASE=GestorAulasIT
      - DB_USERNAME=GestorAulasIT
      - DB_PASSWORD=GestorAulasIT
    networks:
      - GestorAulasIT_net
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db_prod
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: GestorAulasIT
      MYSQL_USER: GestorAulasIT
      MYSQL_PASSWORD: GestorAulasIT
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - GestorAulasIT_net

networks:
  GestorAulasIT_net:
    driver: bridge

volumes:
  db_data:
